"""add coin_codes

Revision ID: 5f35df79e088
Revises: efbeaa11d308
Create Date: 2026-06-15 15:04:50.340924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f35df79e088'
down_revision: Union[str, Sequence[str], None] = 'efbeaa11d308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_codes', 'redeemed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_codes', sa.Column('redeemed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
