"""add buzz_coins

Revision ID: bc157ad29076
Revises: 5f35df79e088
Create Date: 2026-06-15 23:29:00.025781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc157ad29076'
down_revision: Union[str, Sequence[str], None] = '5f35df79e088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buzz_coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'buzz_coins')
    # ### end Alembic commands ###
