"""initial

Revision ID: ccae1a844365
Revises: 
Create Date: 2026-06-14 17:03:19.252445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccae1a844365'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('murmel_enabled', sa.Boolean(), nullable=True),
    sa.Column('murmel_interval', sa.Integer(), nullable=True),
    sa.Column('murmel_duration', sa.Integer(), nullable=True),
    sa.Column('custom_input', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_Settings_username'), 'Settings', ['username'], unique=False)
    op.create_table('game_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_history_id'), 'game_history', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id_banned', sa.Boolean(), nullable=True),
    sa.Column('show_in_leaderboard', sa.Boolean(), nullable=True),
    sa.Column('total_gold_earned', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_game_history_id'), table_name='game_history')
    op.drop_table('game_history')
    op.drop_index(op.f('ix_Settings_username'), table_name='Settings')
    op.drop_table('Settings')
    # ### end Alembic commands ###
